name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - matplotlib
  - pip:
    - submodules/simple-knn
    - submodules/ges_rasterization_init2D
    - submodules/ges_rasterization_surfel
    - submodules/ges_rasterization_surfel_reg
    - submodules/ges_rasterization_joint_s
    - submodules/ges_rasterization_joint_g
    - opencv-python
    - joblib
